### ISSUE TITLE
Calling detect intent method does not result in a response

### ISSUE THREAD

**Issue by apathetic-ryuko** [googleapis/python-dialogflow#237] opened 2020-12-06 02:55 UTC
Hello, i am using python dialogflow library following these instructions 
https://cloud.google.com/dialogflow/es/docs/api-overview
https://googleapis.dev/python/dialogflow/latest/gapic/v2/api.html

and running the sample code does not result in a successful response
`response = client.detect_intent(session, query_input)`

I've tried to debug it and it seems to retry the request with 220 seconds timeout.
And if you wait long enough the following error can be got:
google.api_core.exceptions.RetryError: Deadline of 220.0s exceeded while calling functools.partial

I also wrote to google dialogflow support, but i am currently using trial plan and the web demo works fine, so it may be my client/code or the python library issue. Can anybody help?

traceback: https://pastebin.com/x1F3KmmD
[screencast](https://monosnap.com/file/WJVw7wCNWLoxlhD2k1DD2KmPBG5aal)

OS: Win 10 x64
Python 3.9.0
dialogflow version: 1.1.0

**Comment by apathetic-ryuko** [comment] 2020-12-06 06:34
ok, figured it out that creating the client as `client = dialogflow.SessionsClient(credentials='%path_to_service_accoun.json%')` does not work anymore despite [this stackoverflow answer](https://stackoverflow.com/a/50546430).

and if we set environment variable via os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = '%path_to_service_account.json%' than everything works fine. (like in [that medium article](https://medium.com/swlh/working-with-dialogflow-using-python-client-cb2196d579a4))

**Comment by munkhuushmgl** [comment] 2020-12-07 21:51
@apathetic-ryuko Glad you figured out.

If I understand your concern correctly, your suggestion to get better error message rather than two following?
```google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request'
```
or 
```
RetryError
```

**Comment by zephiroth19** [comment] 2020-12-09 14:32
my concern is that one can't find out where the problem is.
the following line `client = dialogflow.SessionsClient(credentials='%path_to_service_accoun.json%')` should've posted error message like the "argument does not fit type _google.auth.credentials.Credentials_" or smth..

session somehow was created, but wasn't functional and 503 Unavailable does not tell you much about the problem :/

or maybe when executing `client.detect_intent(session, query_input)` invalid session could be identified before trying a delayed request.

**Comment by apathetic-ryuko** [comment] 2020-12-09 14:33
my concern is that one can't find out where the problem is.
the following line client = dialogflow.SessionsClient(credentials='%path_to_service_accoun.json%') should've posted error message like the "argument does not fit type google.auth.credentials.Credentials" or smth..

session somehow was created, but wasn't functional and 503 Unavailable does not tell you much about the problem :/

or maybe when executing client.detect_intent(session, query_input) invalid session could be identified before trying a delayed request.

**Comment by b-loved-dreamer** [comment] 2021-04-27 00:00
Hi @apathetic-ryuko — this is a late reply, but if still relevant, I found a few resources for you: 

https://cloud.google.com/dialogflow/es/docs/quick/setup
https://cloud.google.com/dialogflow/es/docs/how/detect-intent-stream

Please try this readings. I am going to close this issue, but if need to reopen, feel free to do so.

**Closed by b-loved-dreamer** 2021-04-27 00:00 UTC
Labels: api: dialogflow, status: investigating
