### ISSUE TITLE
Streaming: single_utterance parameter only has effect in InputAudioConfig

### ISSUE THREAD

**Issue by csestili** [googleapis/python-dialogflow#177] opened 2020-02-11 20:07 UTC
While trying to detect intent from audio stream, `dialogflow.types.StreamingDetectIntentRequest` is supposed to accept a parameter `single_utterance` such that when `single_utterance == True`, Dialogflow will detect the end of speech and then attempt to resolve the intent.

I was only able to get this behavior working while setting `single_utterance=True` in the parameters for `dialogflow.types.InputAudioConfig`. It seems that this parameter is ignored for `StreamingDetectIntentRequest` but not for `InputAudioConfig`.

If this is intended behavior, could someone please update the [doc](https://cloud.google.com/dialogflow/docs/detect-intent-stream) for future developers? Additionally, it would be super helpful if the streaming doc included an example of streaming audio rather than mock streaming from an audio file.

#### Environment details

1. **OS type and version:** Ubuntu 18.04.4 LTS
2. **Python version and virtual environment information:** Python 3.6.9
3. **dialogflow version:** 0.7.2

#### Steps to reproduce

  1. Install PyAudio.
  2. Connect a microphone to your computer.
  3. In the code example below, set project ID and application credentials path to a test Dialogflow project.
  4. Run the code example and see that speech is being recognized, but intents are not being detected, even though in `StreamingDetectIntentRequest` the `single_utterance` parameter is set to `True`.
  5. Add `single_utterance=True` to the arguments of the `InputAudioConfig` class constructor.
  6. Re-run the code example and see that speech is being recognized, and that intents are being detected after speech stops.

#### Code example

```python
import os

import pyaudio

class DialogflowSession(object):
    """Get Dialogflow intents from audio stream."""

    def __init__(self):
        # Set Google app credentials to enable Dialogflow.
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = <svckey json path>

        self._project_id = <test project id>
        # Using the same `session_id` between requests allows continuation of the conversation.
        self._session_id = None
        self._language_code = 'en'

        self.__sessions_client = None
        self.__session = None

        self.__audio_stream = None

    @property
    def _sessions_client(self):
        if self.__sessions_client is None:
            self.__sessions_client = dialogflow.SessionsClient()
        return self.__sessions_client

    @property
    def _session(self):
        if self.__session is None:
            self.__session = self._sessions_client.session_path(self._project_id, self._session_id)
        return self.__session

    @property
    def _audio_stream(self):
        if self.__audio_stream is None:
            # init stream (TODO move into own func)
            sample_rate = 44100 # 16000 is prob fine for speech
            chunk = 1024  # Record in chunks of 1024 samples
            sample_format = pyaudio.paInt16  # 16 bits per sample
            channels = 1

            p = pyaudio.PyAudio()  # Create an interface to PortAudio

            print('Recording')

            self.__audio_stream = p.open(format=sample_format,
                            channels=channels,
                            rate=sample_rate,
                            frames_per_buffer=chunk,
                            input=True)
        return self.__audio_stream

    # from https://cloud.google.com/dialogflow/docs/detect-intent-stream#streaming_detect_intent
    def detect_intent_stream(self, audio_file_path, do_stream=True):
        """Returns the result of detect intent with streaming audio as input.

        Using the same `session_id` between requests allows continuation
        of the conversation."""
        import dialogflow_v2 as dialogflow
        session_client = dialogflow.SessionsClient()

        # Note: hard coding audio_encoding and sample_rate_hertz for simplicity.
        audio_encoding = dialogflow.enums.AudioEncoding.AUDIO_ENCODING_LINEAR_16
        sample_rate_hertz = 44100 # 16000 is prob fine for speech

        session_path = session_client.session_path(self._project_id, self._session_id)
        print('Session path: {}\n'.format(session_path))

        def request_generator(audio_config, audio_file_path):
            query_input = dialogflow.types.QueryInput(audio_config=audio_config)

            # The first request contains the configuration.
            yield dialogflow.types.StreamingDetectIntentRequest(
                session=session_path, query_input=query_input)

            if not do_stream:
                # Here we are reading small chunks of audio data from a local
                # audio file.  In practice these chunks should come from
                # an audio input device.
                with open(audio_file_path, 'rb') as audio_file:
                    while True:
                        chunk = audio_file.read(4096)
                        if not chunk:
                            break
                        # The later requests contains audio data.
                        yield dialogflow.types.StreamingDetectIntentRequest(
                            input_audio=chunk)

            else:
                while True:
                    chunk = self._audio_stream.read(4096)
                    if not chunk:
                        break
                    # The later requests contains audio data.
                    yield dialogflow.types.StreamingDetectIntentRequest(
                        input_audio=chunk, single_utterance=True)

        audio_config = dialogflow.types.InputAudioConfig(
            audio_encoding=audio_encoding, language_code=self._language_code,
            sample_rate_hertz=sample_rate_hertz) # Add `single_utterance=True` to make it work!

        requests = request_generator(audio_config, audio_file_path)
        responses = session_client.streaming_detect_intent(requests)

        print('=' * 20)
        for response in responses:
            msg = """
Transcript: {}
Query text: {}
Intent: {}
Confidence: {}
            """.format(
                response.recognition_result.transcript,
                response.query_result.query_text,
                response.query_result.intent.display_name,
                response.query_result.intent_detection_confidence
            )
            print(msg)


        # Note: The result from the last response is the final transcript along
        # with the detected content.
        query_result = response.query_result

        print('=' * 20)
        print('Query text: {}'.format(query_result.query_text))
        print('Detected intent: {} (confidence: {})\n'.format(
            query_result.intent.display_name,
            query_result.intent_detection_confidence))
        print('Fulfillment text: {}\n'.format(
            query_result.fulfillment_text))

session = DialogflowSession()
audio_fname = None # audio_fname doesn't matter because we're streaming
session.detect_intent_stream(audio_fname)

```

**Comment by nnegrey** [comment] 2020-03-09 17:21
Hi, `single_utterance` inside StreamingDetectIntentRequest is deprecated. 
https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#streamingdetectintentrequest

I've filed a bug to get that page updated. 

@busunkim96, do our libraries have any warnings for deprecated fields? I tried to use it and nothing came up.

**Comment by nnegrey** [comment] 2020-03-09 19:12
There is this sample PR that might be worth looking at and I'm unable to reproduce the issue with the sample code, everything seems to work as expected. 

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2566/files

**Comment by busunkim96** [comment] 2020-03-09 19:40
No, I think the only indication of a field being deprecated is in the docstring. See https://github.com/googleapis/dialogflow-python-client-v2/blob/713846b7ed99eaf78cdf383aa9d39b43731b9a0d/dialogflow_v2beta1/proto/session_pb2.py#L2422-L2434

**Comment by b-loved-dreamer** [comment] 2021-02-03 20:48
Hi @csestili, I was able to reproduce this issue. We are currently addressing this situation. Thank you for taking note of this.

**Comment by b-loved-dreamer** [comment] 2021-02-16 19:40
Closing this issue as [resolved](https://cloud.google.com/dialogflow/es/docs/how/detect-intent-stream).

**Closed by b-loved-dreamer** 2021-02-16 19:40 UTC
Labels: api: dialogflow, external, triage me
